### ISSUE TITLE
Copy Embededded blocks in the exported file.

### ISSUE THREAD

**Issue by uroybd** [bingryan/obsidian-markdown-export-plugin#12]
Often files got embedded from other files. It will be very helpful if the plugin can copy the embedded section in the output markdown file.

**Comment by bingryan** [comment]
> Often files got embedded from other files. It will be very helpful if the plugin can copy the embedded section in the output markdown file.

Can you provide a case?

**Comment by uroybd** [comment]
The source document:

```md
---
title: "Van Gogh on Art and Artists: Letters to Emile Bernard by Vincent Van Gogh"
updated: 2022-10-09T04:17:36+06:00
created: 2022-10-07T04:28:29+06:00
latitude: 21.30876167
longitude: 92.04272667
altitude: -74.6
tags:
 - "letters"
 - "classic"
 - "art"
---
# Van Gogh on Art and Artists: Letters to Emile Bernard
##### Van Gogh, Vincent

## VI - ARLES: MID-JUNE 1888

### Highlight (yellow) - Location 609

More and more it seems to me that the pictures which must be painted to make present- day painting completely itself and raise it to a height equal to the serene peaks which were attained by the Greek sculptors, the German musicians, and the French novelists, are beyond the power of one isolated individual. They will therefore probably

## VII - ARLES: ABOUT 20TH JUNE 1888

### Highlight (blue) - Location 710

I painted it with the mistral10 raging, my easel fixed to the ground with iron stakes, a trick I recommend to you. One sticks the legs of the easel firmly into the ground, then by their side one drives in an iron stake about 2 ft. long: then one binds them all together with cords. Like that you can work in a wind. ^2c6a8d
```

The document to export, notice how the blocks are being referred:

```md
Embeded Content

![[Personal/Van Gogh on Art and Artists#VI - ARLES: MID-JUNE 1888]]


![[Van Gogh on Art and Artists#^2c6a8d]]

Normal text

![[Media/bbwy.png]]
```


It gets rendered like this:

<img width="1025" alt="Screenshot 2022-12-20 at 2 06 03 PM" src="https://user-images.githubusercontent.com/4207230/208615329-0ebfb3c9-4ea5-420b-89d2-2be17f755895.png">

I want the embedded sections inline in the exported document like this:

```md
Embeded Content

More and more it seems to me that the pictures which must be painted to make present- day painting completely itself and raise it to a height equal to the serene peaks which were attained by the Greek sculptors, the German musicians, and the French novelists, are beyond the power of one isolated individual. They will therefore probably

I painted it with the mistral10 raging, my easel fixed to the ground with iron stakes, a trick I recommend to you. One sticks the legs of the easel firmly into the ground, then by their side one drives in an iron stake about 2 ft. long: then one binds them all together with cords. Like that you can work in a wind.

Normal text

!()[Media/bbwy.png]
```

I was toying with this plugin, But have limited knowledge of Obsidian's API. I've modified your regex to distinguish between attachments and embeds. Here are the regexes:

```ts
export const ATTACHMENT_URL_REGEXP = /!\[\[((.*?)\.(\w+))\]\]/g;
export const EMBED_URL_REGEXP = /!\[\[(.*?)\]\]/g;
```

**Comment by bingryan** [comment]
@uroybd Hey uroybd, this is great idea, if you are willing to try this PR, you can write this logic from here:
https://github.com/bingryan/obsidian-markdown-export-plugin/blob/6774a177542f6bfff8d47d0ee53403a0907c9377/src/utils.ts#L156

BTW, take a look at the overall [obsidian-api](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts),and then you'll be able to implement it.

Finally, if you have difficulty implementing it, I will add this feature sometime.

Do you want to try it?
