### ISSUE TITLE
RequestError [HttpError]: Resource not accessible by integration

### ISSUE THREAD

**Issue by bingryan** [bingryan/obsidian-markdown-export-plugin#15]
When a new contributor works on a CICD , the job fails with the error:

> "Resource not accessible by integration"

see: https://github.com/actions/first-interaction/issues/10

**Comment by uroybd** [comment]
Can you try with write permission in job level like this? https://github.com/rossbar/numpy/blob/866fed5f2362975a669eaa44ebbbf2ebf2fb8047/.github/workflows/circleci.yml
