### ISSUE TITLE
Make Markdown settings a dropdown with 3 options. Github, standard, and None

### ISSUE THREAD

**Issue by Treygec** [bingryan/obsidian-markdown-export-plugin#25]
```
		// TODO: Make Markdown settings a dropdown with 3 options. Github, standard, and None
```

https://github.com/Treygec/obsidian-markdown-export-plugin/blob/0e2733117fa89857386b60d817ee4c01fa5d139c/src/main.ts#L109

**Comment by bingryan** [comment]
@Treygec hey treygec, are you working on this PR? or you just want add a feature issue?

**Comment by Treygec** [comment]
Hi,
I am working on this along with a few other changes. Thought I pushed this
to my own fork but it looks like it rolled up to yours sorry!
