### ISSUE TITLE
failed to use

### ISSUE THREAD

**Issue by Judong0x0** [bingryan/obsidian-markdown-export-plugin#26]
After downloading the plug-in and clicking export all to package, there is no picture in the attachment folder. The picture link in the markdown file still points to the picture in my original attachment folder.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/95458578/211282923-9b64fda2-50f3-467f-a3f1-a209de207cd4.png">

**Comment by bingryan** [comment]
@Judong0x0 thanks for your issue

**Comment by bingryan** [comment]
@Judong0x0 hey Judong0x0, can you show you obsidian's. `Files & Links -> Attactment folder path`?

**Comment by bingryan** [comment]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/41174435/211296957-1b94196f-1031-4903-869d-b98bc319e94b.png">
like this

**Comment by Judong0x0** [comment]
My setup is the same as yours, but I additionally use this addon folder handling plugin. He will change the secondary directory under the attachment directory to the note name.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/95458578/211438889-d64a4755-bc2e-4626-b825-11128eebf413.png">
