### ISSUE TITLE
【feature request】Support other file format like .pptx .doc etc.

### ISSUE THREAD

**Issue by Ravenclawer** [bingryan/obsidian-markdown-export-plugin#27]
This plugin fill in one of the feature gap that obsidian failed for a long time to bridge - export the attachment in a note to a designated folder, but for now this plugin only support picture format. since obsidian support all kinds of attachment formats in the vault, it is possible that one might link to some file like .ini or .zip etc. using wikilinks, so it's better for the plugin to support other formats to fulfill it's maximum potential.

**Comment by Ravenclawer** [comment]
This is a grate plugin, if it support other file extension, it will be better.

**Comment by bingryan** [comment]
> This plugin fill in one of the feature gap that obsidian failed for a long time to bridge - export the attachment in a note to a designated folder, but for now this plugin only support picture format. since obsidian support all kinds of attachment formats in the vault, it is possible that one might link to some file like .ini or .zip etc. using wikilinks, so it's better for the plugin to support other formats to fulfill it's maximum potential.

thanks your issue, some file ext like `.ini , .zip .pub` can't be export to output fold, because the obsidian can't handle `.ini , .zip .pub` file link at content.

**Comment by bingryan** [comment]
> This plugin fill in one of the feature gap that obsidian failed for a long time to bridge - export the attachment in a note to a designated folder, but for now this plugin only support picture format. since obsidian support all kinds of attachment formats in the vault, it is possible that one might link to some file like .ini or .zip etc. using wikilinks, so it's better for the plugin to support other formats to fulfill it's maximum potential.

some file like `.ini or .zip` are also exported, but not show at content/window

**Comment by bingryan** [comment]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/41174435/215410848-b07c2fee-7ae9-4498-8151-ee61d8a50d61.png">
 `epub`
