### ISSUE TITLE
Mardown documents and pictures can only be used in the same folder, and cannot be called from a specific attachment folder

### ISSUE THREAD

**Issue by Judong0x0** [bingryan/obsidian-markdown-export-plugin#30]
Found the reason why it can't be used all the time. Blue Topaz can't be used！！！！

**Comment by Judong0x0** [comment]
Can I add an option box to add a specific attachment folder name

**Comment by bingryan** [comment]
> Blue Topaz

I'm using the Blue Topaz theme now😅

**Comment by bingryan** [comment]
> Can I add an option box to add a specific attachment folder name

yes, go to plugin' setting

**Comment by bingryan** [comment]
Related issue:#26

**Comment by bingryan** [comment]
@Judong0x0 update this plugin, try again
