### ISSUE TITLE
Sorry，This is the last time I mention lssues

### ISSUE THREAD

**Issue by Judong0x0** [bingryan/obsidian-markdown-export-plugin#32]
Finally, I found the cause of the problem, because I used a non-Wiki link, and the plug-in could not read the pictures that were not wiki links.

This is my configuration. Wiki links are closed here
<img width="950" alt="image" src="https://user-images.githubusercontent.com/95458578/220813551-12dae6f4-b137-4517-9063-df64bdb8d076.png">

This export fails
<img width="872" alt="image" src="https://user-images.githubusercontent.com/95458578/220813679-69553b48-cfbe-428a-9af5-9ed525be5a8c.png">

Pictures linked with wiki can be used normally
<img width="973" alt="image" src="https://user-images.githubusercontent.com/95458578/220813885-ca2e3926-1043-40de-b71f-66fd52f83e90.png">

Therefore, can you add the export function in the form of non-wiki links. Thank you very much.

**Comment by bingryan** [comment]
sure 🤓

**Comment by bingryan** [comment]
@Judong0x0 updated 🤓
