### ISSUE TITLE
Doesn't copy attachments from URI escaped markdown links

### ISSUE THREAD

**Issue by mnaoumov** [bingryan/obsidian-markdown-export-plugin#34]
If you have an attachment like `![](hello%20world.pdf)`, it won't be copied to the output folder

**Comment by bingryan** [comment]
maybe you have  turned off the default `FILEs & LInks -> Use [[wiki links]]`

**Comment by bingryan** [comment]
If you are interested in this PR, you can try to make this logical: use !()[] when it is closed, and [[]] when it is open :)
