### ISSUE TITLE
Duplicate file paths

### ISSUE THREAD

**Issue by Barsello** [bingryan/obsidian-markdown-export-plugin#45]
Hi.
Problem. Duplicate files appear when exporting. Which disappear only after rebooting Obsidian.

![Screenshot](https://github.com/bingryan/obsidian-markdown-export-plugin/assets/138699246/633abcea-c3ff-434b-af32-2fecb872ff31)

**Comment by bingryan** [comment]
there is no logical cache and custom event :)

**Comment by bingryan** [comment]
Is there another plugin causing this problem?

**Comment by Barsello** [comment]
Tested on pure Obsidian only with this plugin installed.
Apparently this is such a feature on windows, there is no such thing on MAC.
