### ISSUE TITLE
Custom paths don't seem to work outside of vault

### ISSUE THREAD

**Issue by cassidoo** [bingryan/obsidian-markdown-export-plugin#52]
I tried setting it up so that it would copy a file into a folder outside of my vault:

```
~/GitHub/blog/src/posts
```

And it doesn't seem to work, even though I get a success message.

Edit: it works, it just created a folder structure in my vault, with the top folder being called ~, then GitHub, etc.

**Comment by bingryan** [comment]
@cassidoo update this plugin, and try again :)

> \[!IMPORTANT]
>
> if you want set output outside of vault, set output use os absolute path, such as: `/Users/xxx/Documents/Output`

**Comment by cassidoo** [comment]
Oh heck, thank you!! I'm so excited!

**Comment by cassidoo** [comment]
I meant to post before: this works great! 

> [!NOTE]
> The assets path should be **relative to the markdown output's folder**!

**Comment by bingryan** [comment]
> I meant to post before: this works great!
> 
> Note
> 
> The assets path should be **relative to the markdown output's folder**!

Thanks for your tip 👍

**Comment by Psypher1** [comment]
I have tried this `/Users/Dante/Documents/blogs` and the markdown are exporting to the within the vault, not outside it. Help please

**Comment by cassidoo** [comment]
I wrote about it here!!

https://blog.cassidoo.co/post/publishing-from-obsidian/

**Comment by Psypher1** [comment]
> I wrote about it here!!
> 
> https://blog.cassidoo.co/post/publishing-from-obsidian/

I actually came from your article 😅

**Comment by cassidoo** [comment]
@Psypher1 hahaha awesome! If your computer isn't Linux/Mac maybe you have to use \ instead? I'll try on my PC!

**Comment by Licknstick** [comment]
> Oh heck, thank you!! I'm so excited!

**Comment by Psypher1** [comment]
> @Psypher1 hahaha awesome! If your computer isn't Linux/Mac maybe you have to use \ instead? I'll try on my PC!

I'll give that a go

**Comment by bingryan** [comment]
windows test is ok, update this plugin and try again :)

> \[!IMPORTANT]
>
> if you want set output outside of vault, set output use os absolute path, such as
> 
> Mac/Linux: `/Users/xxx/Documents/Output`
> Windows: `C:\Users\xxx\Documents\Output`
>
> The assets path should be relative to the markdown output's folder!
