### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by sxr1223** [bingryan/obsidian-markdown-export-plugin#59]
Obsidian v1.5.3
plugin v1.0.14
OS win10

Command line and the option in menu isn't work. Please give me some help, thank you.

console log as below:

```
app.js:1 Plugin failure: obsidian-markdown-export-plugin DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at MarkdownExportPlugin. (app://obsidian.md/app.js:1:2023005)
    at app://obsidian.md/app.js:1:237258
    at Object.next (app://obsidian.md/app.js:1:237363)
    at a (app://obsidian.md/app.js:1:236081)
```

**Comment by bingryan** [comment]
> Obsidian v1.5.3 plugin v1.0.14 OS win10
> 
> Command line and the option in menu isn't work. Please give me some help, thank you.
> 
> console log as below:
> 
> ```
> app.js:1 Plugin failure: obsidian-markdown-export-plugin DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
>     at MarkdownExportPlugin. (app://obsidian.md/app.js:1:2023005)
>     at app://obsidian.md/app.js:1:237258
>     at Object.next (app://obsidian.md/app.js:1:237363)
>     at a (app://obsidian.md/app.js:1:236081)
> ```

I can't reproduce it. show more information plz

**Comment by sxr1223** [comment]
Maybe the reason of this issue is plugins conflicts. But how could I find which plugin causes this issue?

**Comment by bingryan** [comment]
> Maybe the reason of this issue is plugins conflicts. But how could I find which plugin causes this issue? Maybe there are some quick methods?

you can try new vault, and only install this plugin.
