### ISSUE TITLE
Invalid count value: -1

### ISSUE THREAD

**Issue by WHG555** [bingryan/obsidian-markdown-export-plugin#61]
# 问题说明 
使用了export to markdown命令，出现了如下错误
```
plugin:obsidian-markdown-export-plugin:379 Uncaught (in promise) RangeError: Invalid count value: -1
    at String.repeat (<anonymous>)
    at getClickSubRoute (plugin:obsidian-markdown-export-plugin:379:22)
    at eval (plugin:obsidian-markdown-export-plugin:483:31)
```

obsidian版本:: 1.1.16

# 这是可以复现错误的ob库
[https://github.com/WHG555/share/releases/download/ob-plugin-test/markdown.zip](https://github.com/WHG555/share/releases/download/ob-plugin-test/markdown.zip)

**Comment by bingryan** [comment]
@WHG555 update this plugin, and try again :)

**Comment by WHG555** [comment]
它已经可以使用使用了。
very good!!!
