### ISSUE TITLE
change output file link format

### ISSUE THREAD

**Issue by kysshsy** [bingryan/obsidian-markdown-export-plugin#81]
I export my note to my blog folder. The file links to attachments are like 'attachments/xxx'，but it seem that my blog can't parse them correctly. I want to change their format to './attachments/xxx'. How can I do? Thank you

<img width="653" alt="image" src="https://github.com/bingryan/obsidian-markdown-export-plugin/assets/73871299/ea232416-4888-4e90-94d6-d827f54d0f80">

to

<img width="705" alt="image" src="https://github.com/bingryan/obsidian-markdown-export-plugin/assets/73871299/2e57ba71-2606-412c-9e32-8e3569a0e758">

**Comment by bingryan** [comment]
> but it seem that my blog can't parse them correctly

maybe you should check your blog software setting.

**Comment by kysshsy** [comment]
thank you for response. I learn and check the blog setting, solve it by change the path of storing images. TY
